name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4    
      - name: Pull the Docker image
        run: sudo docker pull swaruph4/rooktownbot:latest
      - name: Stop the running container
        run: sudo docker stop rooktownbot-container || true
      - name: Remove the container
        run: sudo docker rm -f rooktownbot-container || true      
      - name: Debug workspace
        run: ls -l $GITHUB_WORKSPACE
      - name: Create .env file
        run: |
          echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" > .env
          echo "HENRIKDEV_API_KEY=${{ secrets.HENRIKDEV_API_KEY }}" >> .env
          echo "DATABASE_URL=jdbc:sqlite:/bot/db/RookTownBotDB" >> .env
          echo "LEADERBOARD_IMAGES_PATH=/bot/images/leaderboard/" >> .env
          echo "SCOREBOARD_IMAGES_PATH=/bot/images/scoreboard/" >> .env
      - name: Run Docker compose
        run: sudo docker compose up -d

