name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Pull the Docker image
        run: sudo docker pull swaruph4/rooktownbot:latest
      - name: Stop the running container
        run: sudo docker stop rooktownbot-container || true
      - name: Remove the container
        run: sudo docker rm -f rooktownbot-container || true
      - name: Run Docker compose
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          HENRIKDEV_API_KEY: ${{ secrets.HENRIKDEV_API_KEY }}
        run: sudo docker-compose up -d
