name: RookTownBot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build project
        run: gradle shadowJar --no-daemon

      # Step 4: Deploy to AWS
      - name: Deploy to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i "$SSH_PRIVATE_KEY" ubuntu@<EC2-PUBLIC-IP> << EOF
          cd /home/ubuntu/RookTownBot
          git pull origin main
          pkill -f 'java -jar'
          nohup java -jar RookTownBot.jar &
          EOF  
